<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>MaxBots.Client</AssemblyName>
    <RootNamespace>MaxBots</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>MaxBots.Client</PackageId>
    <Description>HTTP-клиент для Max Bot API.</Description>
    <PackageTags>max;maxbot;api;client</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaxBots.Meta\MaxBots.Meta.csproj" />
  </ItemGroup>
</Project>
