<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>MaxBots.LongPolling</AssemblyName>
    <RootNamespace>MaxBots</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>MaxBots.LongPolling</PackageId>
    <Description>Long Polling для получения апдейтов Max Bot API.</Description>
    <PackageTags>max;maxbot;api;longpolling</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaxBots.Meta\MaxBots.Meta.csproj" />
    <ProjectReference Include="..\MaxBots.Client\MaxBots.Client.csproj" />
  </ItemGroup>
</Project>
